# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Regin
tagline:          'Gudarnas återkomst'
description:      'Du är Regin, ett gudomligt väsen som har kraft att forma världarna. Regin - Lajvet för kreativa spelare som vill forma sin karaktärs och världens utveckling.'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Patrik'
  url:            https://www.mumma.nu

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/paven/lanyon/regin

gems:
- jekyll-mentions
- jekyll-sitemap

